# Updated with FantasyPros Consensus Superflex Rankings & Tiers
DEFAULT_PLAYERS = [
    {
        "Rank": 1,
        "Name": "Josh Allen",
        "Pos": "QB",
        "Team": "BUF",
        "Tier": 1,
        "Bye": 7,
    },
    {
        "Rank": 2,
        "Name": "Lamar Jackson",
        "Pos": "QB",
        "Team": "BAL",
        "Tier": 1,
        "Bye": 13,
    },
    {
        "Rank": 3,
        "Name": "Drake Maye",
        "Pos": "QB",
        "Team": "NE",
        "Tier": 1,
        "Bye": 11,
    },
    {
        "Rank": 4,
        "Name": "Joe Burrow",
        "Pos": "QB",
        "Team": "CIN",
        "Tier": 1,
        "Bye": 6,
    },
    {
        "Rank": 5,
        "Name": "Jayden Daniels",
        "Pos": "QB",
        "Team": "WAS",
        "Tier": 1,
        "Bye": 7,
    },
    {
        "Rank": 6,
        "Name": "Jalen Hurts",
        "Pos": "QB",
        "Team": "PHI",
        "Tier": 2,
        "Bye": 10,
    },
    {
        "Rank": 7,
        "Name": "Bijan Robinson",
        "Pos": "RB",
        "Team": "ATL",
        "Tier": 2,
        "Bye": 11,
    },
    {
        "Rank": 8,
        "Name": "Jahmyr Gibbs",
        "Pos": "RB",
        "Team": "DET",
        "Tier": 2,
        "Bye": 6,
    },
    {
        "Rank": 9,
        "Name": "Ja'Marr Chase",
        "Pos": "WR",
        "Team": "CIN",
        "Tier": 2,
        "Bye": 6,
    },
    {
        "Rank": 10,
        "Name": "Justin Herbert",
        "Pos": "QB",
        "Team": "LAC",
        "Tier": 2,
        "Bye": 7,
    },
    {
        "Rank": 11,
        "Name": "Caleb Williams",
        "Pos": "QB",
        "Team": "CHI",
        "Tier": 2,
        "Bye": 10,
    },
    {
        "Rank": 12,
        "Name": "Puka Nacua",
        "Pos": "WR",
        "Team": "LAR",
        "Tier": 2,
        "Bye": 11,
    },
    {
        "Rank": 13,
        "Name": "Jaxon Smith-Njigba",
        "Pos": "WR",
        "Team": "SEA",
        "Tier": 2,
        "Bye": 11,
    },
    {
        "Rank": 14,
        "Name": "Trevor Lawrence",
        "Pos": "QB",
        "Team": "JAC",
        "Tier": 2,
        "Bye": 7,
    },
    {
        "Rank": 15,
        "Name": "Dak Prescott",
        "Pos": "QB",
        "Team": "DAL",
        "Tier": 2,
        "Bye": 14,
    },
    {
        "Rank": 16,
        "Name": "Amon-Ra St. Brown",
        "Pos": "WR",
        "Team": "DET",
        "Tier": 3,
        "Bye": 6,
    },
    {
        "Rank": 17,
        "Name": "Christian McCaffrey",
        "Pos": "RB",
        "Team": "SF",
        "Tier": 3,
        "Bye": 8,
    },
    {
        "Rank": 18,
        "Name": "Jonathan Taylor",
        "Pos": "RB",
        "Team": "IND",
        "Tier": 3,
        "Bye": 13,
    },
    {
        "Rank": 19,
        "Name": "CeeDee Lamb",
        "Pos": "WR",
        "Team": "DAL",
        "Tier": 3,
        "Bye": 14,
    },
    {
        "Rank": 20,
        "Name": "Jaxson Dart",
        "Pos": "QB",
        "Team": "NYG",
        "Tier": 3,
        "Bye": 12,
    },
    {
        "Rank": 21,
        "Name": "Brock Purdy",
        "Pos": "QB",
        "Team": "SF",
        "Tier": 3,
        "Bye": 8,
    },
    {
        "Rank": 22,
        "Name": "Justin Jefferson",
        "Pos": "WR",
        "Team": "MIN",
        "Tier": 3,
        "Bye": 6,
    },
    {
        "Rank": 23,
        "Name": "James Cook",
        "Pos": "RB",
        "Team": "BUF",
        "Tier": 3,
        "Bye": 7,
    },
    {
        "Rank": 24,
        "Name": "Bo Nix",
        "Pos": "QB",
        "Team": "DEN",
        "Tier": 3,
        "Bye": 14,
    },
    {
        "Rank": 25,
        "Name": "Patrick Mahomes",
        "Pos": "QB",
        "Team": "KC",
        "Tier": 3,
        "Bye": 10,
    },
]
